name: color_tracked_plz
description: |
  This example showcases how to use the Camera Code Detector Brick to detect barcodes and QR codes and display the results in a web application as well as saving the results to an SQL database.
ports: []
bricks:
- arduino:web_ui: {}
icon: 📦
